platform :ios,'8.0'
target 'GBLW'do
pod 'AFNetworking', '3.1.0'
pod 'Masonry', '1.0.2'
pod 'MBProgressHUD', '1.0.0'
pod 'Mantle', '2.1.0'
pod 'YYWebImage', '1.0.5'
pod 'WebViewJavascriptBridge', '6.0.2'
pod 'MJRefresh', '3.1.14'
pod 'Toast','3.1.0'
end
